POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "sample 2",
	"email": "sample2@email.com",
	"password": "123456",
    "role":"professor"
}

### auth login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "rollie@email.com",
    "password": "123456"
}

### change logged user info
PUT http://localhost:8080/auth/update
Content-Type: application/json

{
    "email": "angelo@email.com",
    "name": "Sir Angelo Garcia",
    "old_password": "123456",
    "new_password": "12345678"
}

### logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

### create professor profile

POST http://localhost:8080/professor/profile
Content-Type: application/json

{
    "year":1,
    "department":"CAm"
}

### get your own profile
GET http://localhost:8080/professor/profile
Content-Type: application/json

### delete your own profile
DELETE http://localhost:8080/professor/profile
Content-Type: application/json

{
    "id":21
}

### add availability
POST http://localhost:8080/professor/availability
Content-Type: application/json

{
    "day":"Monday",
    "start": "12:00:00",
    "end":"13:30:00"
}

### get availability of logged in professor
GET http://localhost:8080/professor/availability
Content-Type: application/json

### get availability of certain professor

POST http://localhost:8080/search/availability
Content-Type: application/json

{
    "id":8
}

### search for professors

POST http://localhost:8080/search/professor
Content-Type: application/json

{
    "name":""
}

### search for prof info:
POST http://localhost:8080/search/professor/info
Content-Type: application/json

{
    "id":8
}

###sending appointment

POST http://localhost:8080/appointment/send
Content-Type: application/json

{
    "prof_id":1,
    "availability_id":1,
    "message":"FROM CPE GE-II, for Emergency",
    "time_stamp":"2025-9-17"
}

### getting appointment
GET http://localhost:8080/appointment/list
Content-Type: application/json

### accepting appointment
POST http://localhost:8080/appointment/accept
Content-Type: application/json

{
    "id":2
}

### update message field of an appointment
POST http://localhost:8080/appointment/update/message
Content-Type: application/json

{
    "id":13,
    "message":"Hello"
}

### deletes a specific appointment

DELETE http://localhost:8080/appointment/delete
Content-Type: application/json

{
    "id": 6
}

### get the appointment booked for the current day
GET http://localhost:8080/appointment/currentDayBooked
Content-Type: application/json

### get currently logged user info
GET http://localhost:8080/user/me
Content-Type: application/json


### count all of total appointments
### time ranges : past, today, tomorrow, future
POST http://localhost:8080/appointments/count
Content-Type: application/json

{
    "status": "confirmed",
    "time_range": "today"
}

### count appointments grouped by status category
POST http://localhost:8080/appointments/groupedCount
Content-Type: application/json

{
    "time_range": "past"
}