POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "test",
	"email": "teacher2@example.com",
	"password": "109726",
    "role":"professor"
}

### auth login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "teacher2@example.com",
    "password":"109726"
}

### create professor profile

POST http://localhost:8080/professor/profile
Content-Type: application/json

{
    "year":1,
    "department":"CAM"
}

### add availability
POST http://localhost:8080/professor/availability
Content-Type: application/json

{
    "day":"Monday",
    "start": "09:00:00",
    "end":"10:30:00"
}