POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "name": "johnny",
	"email": "johnny2@example.com",
	"password": "109726",
    "role":"student"
}

### auth login

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "angelo@email.com",
    "password":"123456"
}

### logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

### create professor profile

POST http://localhost:8080/professor/profile
Content-Type: application/json

{
    "year":1,
    "department":"CEN"
}

### add availability
POST http://localhost:8080/professor/availability
Content-Type: application/json

{
    "day":"Monday",
    "start": "09:00:00",
    "end":"10:30:00"
}

### get availability of logged in professor
GET http://localhost:8080/professor/availability
Content-Type: application/json

### get availability of certain professor

POST http://localhost:8080/search/availability
Content-Type: application/json

{
    "id":8
}

### search for professors

POST http://localhost:8080/search/professor
Content-Type: application/json

{
    "name":""
}

###sending appointment

POST http://localhost:8080/appointment/send
Content-Type: application/json

{
    "prof_id":16,
    "time_stamp":"2025-08-30T02:30:00.000Z"
}

### getting appointment
GET http://localhost:8080/appointment/list
Content-Type: application/json

### accepting appointment
POST http://localhost:8080/appointment/accept
Content-Type: application/json

{
    "id":2
}