POST http://localhost:8080/appointment/send
Content-Type: application/json

{
    "availability_id": "5",
    "message": "Hillo",
    "target_date": "2024-07-01T10:00:00Z"
}

###
POST http://localhost:8080/appointment/list
Content-Type: application/json

{
    "status": "0" //optional
}

###
POST http://localhost:8080/appointment/accept
Content-Type: application/json

{
    "id": "17"
}

###
DELETE http://localhost:8080/appointment/delete
Content-Type: application/json

{
    "id": "12"
}

###
PUT http://localhost:8080/appointment/message/update
Content-Type: application/json

{
    "id": "6",
    "message": "You're my world"
}

### decline appointment
POST http://localhost:8080/appointment/decline
Content-Type: application/json

{
    "id": "17"
}

###
POST http://localhost:8080/appointment/hide
Content-Type: application/json

{
    "ids": [69,70, 90]
}

### get appointments for current day
POST http://localhost:8080/appointment/current-day
Content-Type: application/json

{
    "cursor_id": 0
}

### counts appointment on different time range
POST http://localhost:8080/appointment/count
Content-Type: application/json

{
    "time_range": "today"
}