POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "angelo@email.com",
  "password": "123456"
}
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "angelo@email.com",
  "password": "123456",
  "name": "Angelo",
  "role": "professor"
}

###
GET http://localhost:8080/auth/profile
Content-Type: application/json