POST http://localhost:8080/availability/create
Content-Type: application/json

{
    "day": 7,
    "time_start": "09:00",
    "time_end": "13:00"
}

###
POST http://localhost:8080/availability/createAll
Content-Type: application/json

{
    "availability_list": [
        {
            "day_of_week": 0,
            "start_time": "09:00",
            "end_time": "13:00"
        }
    ]
}

###
GET http://localhost:8080/availability/list
Content-Type: application/json

###
POST http://localhost:8080/availability/user
Content-Type: application/json

{
    "user_id": 3
}

###
DELETE http://localhost:8080/availability/delete
Content-Type: application/json

{
    "id": 2
}