POST http://localhost:8080/course/create
Content-Type: application/json

{
    "name": "CpE",
    "description": "Computer Engineering"
}

### 
POST http://localhost:8080/course/use
Content-Type: application/json

{
    "course_id": 6,
    "year": 1
}

###
GET http://localhost:8080/course/list
Content-Type: application/json

###
POST http://localhost:8080/course/search
Content-Type: application/json

{
    "name": "C"
}

###
POST http://localhost:8080/course/user
Content-Type: application/json

{
    "user_id": "3"
}

###
DELETE http://localhost:8080/course/delete
Content-Type: application/json

{
    "id": "5"
}