### count all unread notifications
GET http://localhost:8080/notification/count/unread
Content-Type: application/json

### mark all unread notifications as read
GET http://localhost:8080/notification/mark-all-read
Content-Type: application/json

### get all unread notifications with pagination
### it uses cursor based pagination
### the end_from is the id of the last notification received
POST http://localhost:8080/notification/list/unread
Content-Type: application/json

{
    "end_from": 0
}

### get all notifications with pagination
### it uses cursor based pagination
### the end_from is the id of the last notification received
POST http://localhost:8080/notification/list/all
Content-Type: application/json

{
    "end_from": 4
}