POST http://localhost:8080/search/professors
Content-Type: application/json

{
    "user_name": "A"
}

###
POST http://localhost:8080/search/professor/user
Content-Type: application/json

{
    "professor_user_id": "2"
}