POST http://localhost:8080/section/enroll
Content-Type:application/json

{
    "section_id": 1
}


### Gets list of all available sections
GET http://localhost:8080/section/list/all
Content-Type: application/json