POST http://localhost:8080/section/enroll
Content-Type:application/json

{
    "section_id": 2
}

### enroll to multiple courses
POST http://localhost:8080/section/enroll/all
Content-Type:application/json

{
    "section_ids": [2,3]
}

### Gets list of all available sections
GET http://localhost:8080/section/list/all
Content-Type: application/json

### Unenroll the logged user from a specific section
POST http://localhost:8080/section/unenroll
Content-Type:application/json

{
    "section_id": 3
}


### Gets list of sections owned by the logged user
GET http://localhost:8080/section/list/owned
Content-Type: application/json